# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d1e2dd2c66b5b09322f5fd609915862d9279f4cd701312d0a39d121aa2ebecde8b7d43b6ad6043001813f870b8a42db2ec97ff5fd8f2d8603d9e6ed9a2f14bb

test:
  secret_key_base: c794e8651165f36058047f2e68ecc67c9d60d99bae0f325def56e071f17f4a768117c0848fb4236b757be6513083c39232cdedc3c19b015177ea8d50fb20af5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
